export { default as Booking} from './booking/Booking'
export { default as Category} from './category/Category'
export { default as Destination} from './destination/Destination'
export { default as Footer} from './footer/Footer'
export { default as Header} from './header/Header'
export { default as Testimonial} from './testimonial/Testimonial'