export { default as Cta } from './cta/Cta'
export { default as Navbar } from './navbar/Navbar'
export { default as DestinationCard } from './destinationCard/DestinationCard'
export { default as ServiceCard } from './serviceCard/ServiceCard' 
export { default as Tips } from './tips/Tips'
export { default as TestimonialCard } from './testimonialCard/TestimonialCard'
export { default as Brands } from './brands/Brands'